image:
  repository: alessiocasco/automerge
  tag: latest
  pullPolicy: Always

serviceAccount:
  annotations:
    my-annotation: "true"
  imagePullSecrets:
    - name: docker-registry
    - name: aws-registry

job:
  schedule: "*/20 4-6 * * *"
  completions: 1
  parallelism: 1
  restartPolicy: Never
  annotations:
    vault.hashicorp.com/agent-cache-enable: "true"
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/agent-pre-populate-only : "true"
    vault.hashicorp.com/role: k8s-tools-automerge
    vault.hashicorp.com/agent-inject-secret-config.json: development-eu-west-1/tools/secret/automerge/config
    vault.hashicorp.com/agent-inject-template-config.json: |
      {{- with secret "development-eu-west-1/tools/secret/automerge/config" -}}
      {{ .Data.data | toJSON  }}
      {{- end }}
  args: ["python", "main.py", "--config", "/vault/secrets/config.json"]
  # args: ["python", "main.py", "--config", "/app/config/config.json"]
  resources:
    requests:
      memory: "64Mi"
      cpu: "500m"
    limits:
      memory: "128Mi"
      cpu: "1000m"

# secret:
#   config: |
#     {
#       "access_token" : "token",
#       "filters" : [
#           "^\\[DEPENDENCIES\\] Update Terraform",
#           "^\\[DEPENDABOT\\]",
#           "^\\[Dependabot\\]"
#       ],
#       "github_user" : "AlessioCasco",
#       "owner" : "AlessioCasco",
#       "repos" : [
#           "terraform-vault",
#           "terraform-aws"
#       ]
#     }
